import type { SearchResponse } from "./types";

/**
 * Réponse mock conforme au contrat `/search`, pour valider le rendu des
 * cartes quand l'index Azure est vide. Activée via VITE_USE_MOCK=true.
 */
export const MOCK_RESPONSE: SearchResponse = {
  count: 4,
  results: [
    {
      id: "eeq_2014__CONF_GOV",
      survey_id: "eeq_2014",
      survey_name: "Étude électorale québécoise 2014 (EEQ)",
      survey_year: 2014,
      pollster: "Université McGill",
      language: "fr",
      variable: "CONF_GOV",
      question_text:
        "Dans quelle mesure faites-vous confiance au gouvernement du Québec?",
      response_options: [
        { code: "1", label: "Beaucoup" },
        { code: "2", label: "Assez" },
        { code: "3", label: "Peu" },
        { code: "4", label: "Pas du tout" },
      ],
      var_type: "scale",
      is_sociodemo: false,
      sociodemo_type: null,
      concepts: ["confiance institutionnelle"],
      themes: ["institutions", "gouvernance"],
      tags: ["electoral", "provincial", "québec"],
      n_respondents: 1517,
      pertinence: "Exact",
      score_couverture: 100,
    },
    {
      id: "eeq_2014__VOTE_INT",
      survey_id: "eeq_2014",
      survey_name: "Étude électorale québécoise 2014 (EEQ)",
      survey_year: 2014,
      pollster: "Université McGill",
      language: "fr",
      variable: "VOTE_INT",
      question_text:
        "Pour quel parti avez-vous l'intention de voter à la prochaine élection?",
      response_options: [
        { code: "1", label: "Parti libéral du Québec" },
        { code: "2", label: "Parti québécois" },
        { code: "3", label: "Coalition avenir Québec" },
        { code: "4", label: "Québec solidaire" },
        { code: "99", label: "Ne sais pas" },
      ],
      var_type: "single",
      is_sociodemo: false,
      sociodemo_type: null,
      concepts: ["intention de vote"],
      themes: ["élections", "partis politiques"],
      tags: ["electoral", "provincial", "québec"],
      n_respondents: 1517,
      pertinence: "Partiel",
      score_couverture: 67,
    },
    {
      id: "cecd_charte_2013_10__CHARTE_APPUI",
      survey_id: "cecd_charte_2013_10",
      survey_name: "Sondage CECD — Charte des valeurs (octobre 2013)",
      survey_year: 2013,
      pollster: "CROP",
      language: "fr",
      variable: "CHARTE_APPUI",
      question_text:
        "Appuyez-vous le projet de Charte des valeurs québécoises?",
      response_options: [
        { code: "1", label: "Tout à fait d'accord" },
        { code: "2", label: "Plutôt d'accord" },
        { code: "3", label: "Plutôt en désaccord" },
        { code: "4", label: "Tout à fait en désaccord" },
      ],
      var_type: "scale",
      is_sociodemo: false,
      sociodemo_type: null,
      concepts: ["laïcité", "valeurs"],
      themes: ["laïcité", "identité"],
      tags: ["charte", "québec", "2013"],
      n_respondents: 1003,
      pertinence: "Faible",
      score_couverture: 33,
    },
    {
      id: "cecd_charte_2013_10__AGE",
      survey_id: "cecd_charte_2013_10",
      survey_name: "Sondage CECD — Charte des valeurs (octobre 2013)",
      survey_year: 2013,
      pollster: "CROP",
      language: "fr",
      variable: "AGE",
      question_text: "Dans quel groupe d'âge vous situez-vous?",
      response_options: [
        { code: "1", label: "18-34 ans" },
        { code: "2", label: "35-54 ans" },
        { code: "3", label: "55 ans et plus" },
      ],
      var_type: "single",
      is_sociodemo: true,
      sociodemo_type: "age",
      concepts: [],
      themes: ["sociodémographie"],
      tags: ["charte", "québec", "2013"],
      n_respondents: 1003,
    },
  ],
};
