import daisyui from "daisyui";
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'font-inter',
    'font-roboto',
    'font-open',
    'font-montserrat',
    'font-nunito',
    'font-source',
    'font-ibm',
    'font-space',
    'font-serif',
    'font-mono',
  ],
  theme: {
    extend: {
      fontFamily: {
      roboto: ['Roboto', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      'open': ['Open Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      'montserrat': ['Montserrat', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      'nunito': ['Nunito', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      'source': ['Source Sans Pro', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      'ibm': ['IBM Plex Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      'space': ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      inter: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      serif: ['Merriweather', 'serif'],
      mono: ['Fira Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      poppins: ['Poppins', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      lato: ['Lato', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      raleway: ['Raleway', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      ubuntu: ['Ubuntu', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      muli: ['Muli', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      work: ['Work Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      nunitosans: ['Nunito Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      quicksand: ['Quicksand', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      rubik: ['Rubik', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      firasans: ['Fira Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
    },
    },
  },
  plugins: [],
}
